
const S={mode:'WEB',profile:null,b:null,chart:null,token:localStorage.getItem('surveyToken')||''};
document.addEventListener('DOMContentLoaded',init);
async function init(){bind();try{await mode_();S.b=await get_('bootstrap');masters();topics();if(S.mode==='LIFF')await existing('LIFF',S.profile.userId)}catch(e){msg(e.message,'err')}}
async function mode_(){try{await liff.init({liffId:APP_CONFIG.LIFF_ID});if(liff.isInClient()){if(!liff.isLoggedIn()){liff.login();return}S.profile=await liff.getProfile();S.mode='LIFF';q('liffBox').classList.remove('hidden');q('lineId').value=S.profile.userId;q('lineName').value=S.profile.displayName;q('mode').textContent='LINE LIFF: '+S.profile.displayName;return}}catch(e){}q('webBox').classList.remove('hidden');q('mode').textContent='ลิงก์ปกติ: ตรวจสอบด้วยอีเมล'}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');q(b.dataset.p).classList.add('active');if(b.dataset.p==='dash')await dash();if(b.dataset.p==='admin'&&S.token)await openAdmin()});q('form').onsubmit=save;q('checkEmail').onclick=()=>existing('WEB',val('email'));q('loginBtn').onclick=login;q('csvBtn').onclick=csv;q('saveSet').onclick=saveSet}
async function get_(a,p={}){const u=new URL(APP_CONFIG.GAS_WEB_APP_URL);u.searchParams.set('action',a);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u),j=await r.json();if(!j.success)throw Error(j.message);return j.data}
async function post_(p){const r=await fetch(APP_CONFIG.GAS_WEB_APP_URL,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify(p)}),j=await r.json();if(!j.success)throw Error(j.message);return j.data}
function masters(){fill('department',S.b.departments,'Department');fill('position',S.b.positions,'Position')}
function fill(id,a,k){q(id).innerHTML='<option value="">เลือก</option>'+a.map(x=>`<option>${x[k]}</option>`).join('')}
function topics(){const g={};S.b.subTopics.forEach(x=>(g[x.TopicID]??=[]).push(x));q('topics').innerHTML=S.b.topics.map((t,i)=>`<div class="card"><h3>${t.Icon} ${i+1}. ${t.TopicName}</h3>${(g[t.TopicID]||[]).map((s,j)=>`<div class="q"><b>${i+1}.${j+1} ${s.SubTopic}</b><div class="scores">${[1,2,3,4,5].map(n=>`<div><input id="${s.SubTopicID}_${n}" name="s_${s.SubTopicID}" type="radio" value="${n}" data-t="${t.TopicID}" data-s="${s.SubTopicID}"><label for="${s.SubTopicID}_${n}">${n}</label></div>`).join('')}</div></div>`).join('')}</div>`).join('')}
async function existing(m,id){if(!id)return msg('กรุณากรอกอีเมล','err');const d=await get_('findResponse',{mode:m,identity:id});if(!d)return msg('ยังไม่พบคำตอบเดิม','info');const h=d.header;set('email',h.Email);set('fullName',h.FullName);set('department',h.Department);set('position',h.Position);set('work',h.WorkExperience);set('skill',h.ComputerSkill);set('training',h.TrainingMode);set('comment',h.Comment);d.answers.forEach(a=>{const e=document.querySelector(`input[name="s_${a.subTopicId}"][value="${a.score}"]`);if(e)e.checked=true});msg('โหลดคำตอบเดิมแล้ว','info')}
async function save(e){e.preventDefault();const a=[...document.querySelectorAll('input[name^="s_"]:checked')].map(x=>({topicId:x.dataset.t,subTopicId:x.dataset.s,score:+x.value}));const p={action:'saveResponse',accessMode:S.mode,lineUserId:S.profile?.userId||'',displayLine:S.profile?.displayName||'',email:val('email'),fullName:val('fullName'),department:val('department'),position:val('position'),workExperience:val('work'),computerSkill:val('skill'),trainingMode:val('training'),comment:val('comment'),answers:a};const d=await post_(p);msg(d.action==='CREATE'?'ส่งเรียบร้อย':'แก้ไขเรียบร้อย','ok')}
async function dash(){const d=await get_('dashboard');q('sTotal').textContent=d.total;q('sDept').textContent=d.departments;q('sLiff').textContent=d.liff;q('sWeb').textContent=d.web;if(S.chart)S.chart.destroy();S.chart=new Chart(q('chart'),{type:'bar',data:{labels:d.topics.map(x=>x.name),datasets:[{data:d.topics.map(x=>x.average)}]},options:{maintainAspectRatio:false,indexAxis:'y',scales:{x:{min:0,max:5}},plugins:{legend:{display:false}}}})}
async function login(){const d=await post_({action:'adminLogin',username:val('au'),password:val('ap')});S.token=d.token;localStorage.setItem('surveyToken',S.token);await openAdmin()}
async function openAdmin(){const s=await post_({action:'adminSettings',token:S.token});q('loginCard').classList.add('hidden');q('console').classList.remove('hidden');set('setOpen',s.SURVEY_OPEN);set('setEdit',s.ALLOW_EDIT);set('setDash',s.DASHBOARD_PUBLIC);set('setDomain',s.REQUIRE_EMAIL_DOMAIN)}
async function saveSet(){await post_({action:'saveSettings',token:S.token,settings:{SURVEY_OPEN:val('setOpen'),ALLOW_EDIT:val('setEdit'),DASHBOARD_PUBLIC:val('setDash'),REQUIRE_EMAIL_DOMAIN:val('setDomain')}});msg('บันทึก Setting แล้ว','ok')}
async function csv(){const d=await post_({action:'exportCsv',token:S.token}),b=atob(d.base64),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);const url=URL.createObjectURL(new Blob([u],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=d.filename;a.click();URL.revokeObjectURL(url)}
function q(i){return document.getElementById(i)}function val(i){return String(q(i)?.value||'').trim()}function set(i,v){if(q(i))q(i).value=v||''}function msg(t,c){const e=q('notice');e.textContent=t;e.className='notice '+c;e.classList.remove('hidden')}
